# Form implementation generated from reading ui file 'ui/LoginForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(523, 300)
        self.passwordField = QtWidgets.QTextEdit(parent=LoginDialog)
        self.passwordField.setGeometry(QtCore.QRect(250, 140, 221, 31))
        self.passwordField.setObjectName("passwordField")
        self.usernameField = QtWidgets.QTextEdit(parent=LoginDialog)
        self.usernameField.setGeometry(QtCore.QRect(250, 70, 221, 31))
        self.usernameField.setObjectName("usernameField")
        self.loginButton = QtWidgets.QPushButton(parent=LoginDialog)
        self.loginButton.setGeometry(QtCore.QRect(370, 220, 93, 28))
        self.loginButton.setObjectName("loginButton")
        self.usernameLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.usernameLabel.setGeometry(QtCore.QRect(250, 50, 91, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameLabel_2 = QtWidgets.QLabel(parent=LoginDialog)
        self.usernameLabel_2.setGeometry(QtCore.QRect(250, 120, 91, 16))
        self.usernameLabel_2.setObjectName("usernameLabel_2")
        self.csuLogo = QtWidgets.QLabel(parent=LoginDialog)
        self.csuLogo.setGeometry(QtCore.QRect(30, 50, 171, 171))
        self.csuLogo.setText("")
        self.csuLogo.setPixmap(QtGui.QPixmap("ui\\../images/csuLogo.png"))
        self.csuLogo.setScaledContents(True)
        self.csuLogo.setObjectName("csuLogo")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login"))
        self.loginButton.setText(_translate("LoginDialog", "Login"))
        self.usernameLabel.setText(_translate("LoginDialog", "Username"))
        self.usernameLabel_2.setText(_translate("LoginDialog", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
